server:
  port: 10086

#定义eureka服务端
eureka:
  client:
    # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    #是否将自己注册到eureka中
    register-with-eureka: false
    #是否从eureka中获取信息
    fetch-registry: false