#定义服务应用名称
spring:
  application:
    name: gateway
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 100000
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: jy-user
          uri: lb://jy-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
        - id: jy-order
          uri: lb://jy-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
        - id: jy-goods
            uri: lb://jy-goods
            predicates:
              - Path=/goods/**
            filters:
              - StripPrefix=1
              - name: Hystrix
                args:
                  name: fallbackcmd
                  fallbackUri: forward:/fallback
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 110000

hystrix:
  command:
    default:
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 120000
        timeout:
          enabled: true
        circuitBreaker:
          sleepWindowInMilliseconds: 5000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 1000
  threadpool:
    default:
      coreSize: 500 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数，默认值-1
      queueSizeRejectionThreshold: 1000 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5

sso:
  oauth2:
    #跳过认证的路由
    ignore-auth-urls:
      - /user/register
      - /sso/oauth/login
      - /sso/oauth/token/refresh
      - /sso/oauth/token
      - /oauth/**
## 开启Swagger的Basic认证功能,默认是false
swagger:
  basic:
    enable: true
    username: admin
    password: admin
